project:
  type: website
  output-dir: docs

website:
  title: "PSTAT 120B"
  favicon: "Images/Logos_Icons/120b_logo.svg"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: Pages/policies.qmd
        text: Syllabus/Policies
      - href: Pages/schedule.qmd
        text: Lectures/Course Schedule
      - href: Pages/course_staff.qmd
        text: Course Staff
      - href: Pages/exams.qmd
        text: Exam Information
      - section: "Resources"
        contents:
          - href: Pages/Resources/notation.qmd
            text: "Statistical Notation"
          - href: Pages/Resources/120arev.qmd
            text: "PSTAT 120A Review"
          - href: Pages/Resources/lec_supp.qmd
            text: "Lecture Supplements"
    logo: "Images/Logos_Icons/120b_logo.svg"
    title: "PSTAT 120B: Summer Session A, 2024"
  page-footer: "Site designed by Ethan P. Marzban using Quarto; ©2024"

format:
  html:
    theme: 
      light: [spacelab, theme.scss]
      dark: [cyborg, theme.scss]
    css: styles.css
    toc: true



