---
title: "PSTAT 120B: Mathematical Statistics, I"
subtitle: "Course Syllabus and Policies"
author:
  - name: "Ethan Marzban"
    affiliations:
      - name: "Summer Session A, 2024"
author-title: "Instructor"
affiliation-title: "Quarter"
format: html
---

Welcome to PSTAT 120B! I am very excited to be your instructor this quarter. Our journey together will take us through the wonders of mathematical statistics, which seeks to form a logically and rigorously sound framework to discuss more advanced statistical topics. Looking forward to a great quarter with y’all! -- Ethan

:::{.callout-note}
## **Lecture Information**

M, T, W, R;	12:30 - 1:35 pm, in ILP 1302
:::



## PDF/Graphical Syllabus

If you prefer a PDF version of this syllabus (including a graphical overview of policies, etc.), please see the following document: 

<style>
.myclass {
  max-width: 100%;
  width: 800px;
  height: 700px;
  border: 10px solid rgba(250, 196, 120, 0.2);
  margin: 0;
}
</style>

{{< pdf ../Files/Misc/120B_PDF_Syllabus.pdf class=myclass >}}

\

## Course Description

The official description of this course, from the UCSB Course Catalog, is:

> Distribution of sample mean and sample variance; t, chi-squared and F distributions; summarizing data by statistics and graphs; estimation theory for single samples: sufficiency, efficiency, consistency, method of moments, maximum likelihood; hypothesis testing: likelihood ratio test; confidence intervals.

This quarter, we will also discuss conditional expectations, to set you up for success in your future PSTAT courses (like PSTAT 160A/B, 131/231, 174/274, etc.)

## Prerequisites

The only prerequisite for this course is a grade of C or higher in PSTAT 120A (Calculus-based probability). We will be using probability extensively this quarter, so please make sure to brush up on your probability knowledge before starting this course.


## Textbook

There is only one required textbook for this course:

-   _Mathematical Statistics with Applications_, 7th edition, by Dennis Wackerly, William Mendenhall, Richard L. Scheaffer.

We will (roughly) cover chapters 6 - 10 and parts of Chapter 14. Readings will be assigned; I ask that you please complete the readings before lecture.

Please note: though the lecture notes I post to the course website are designed to be largely self-contained, studies have shown great benefit to seeing material presented in several different ways. This is why textbooks are very useful, and an integral part of the learning process!


## Course Components

-   **Homework**: there will be one homework assignment due per week, on either Tuesday or Wednesday (please see the tentative [schedule](schedule.qmd)). These will be submitted on Gradescope.

-   **Quizzes:** there will be 3 quizzes  this quarter, administered once per non-exam week. Quizzes will be administered **synchronously and in-person**, at the start of Thursday Discussion Sections, and will last for 20 minutes.

-   **Exams**: there will be a total of three exams this quarter: two midterms, and one final exam. The dates and locations for the exams are:

:::{.callout-important}
## **Exam Dates**

-   **Midterm 1**: Wednesday, July 3, 2024 during Lecture, in the Lecture Hall
-   **Midterm 2**: Wednesday, July 17, 2024 during Lecture, in the Lecture Hall
-   **Final Exam**: Friday, August 2, 2024; **4 - 7pm in ILP 2302** [please note that this is DIFFERENT than our usual classroom]

:::


## Late Work / Accommodations

Unfortunately, we cannot accept any late submissions for any assignments (homework, quizzes,
exams). Instead:

-   Your lowest two (2) HW scores and lowest quiz score will be dropped

-   The lower of your two midterm scores will be dropped or replaced with the average of your remaining midterm score and your final exam score; whichever gives you a higher overall final grade (though you must take all three exams; failure to do so will result in a grade of 'F')

Please also note that our Final Exam is scheduled to take place on the final _**Friday**_ of the quarter. If this Final Exam time conflicts with another Final Exam you are taking, please reach out to me (Ethan)  ASAP to coordinate.

## Course Grades

Your final grade in the course will be computed according to the following scheme:

| **Homework** | **Quizzes** | **Midterms** | **Final Exam** |
|:----:|:-----:|:-----:|:-----:|
| 20\% | 15\% | 15\% each | 35\% |

Furthermore, your final letter grade will be computed according the the following scheme:

-   **A^--^ -- A^+^**: [90, 100]
-   **B^--^ -- B^+^**: [80, 90)
-   **C^--^ -- C^+^**: [70, 80)
-   **D^--^ -- D^+^**: [60, 70)
-   **F**: [0, 60)

Cutoffs between plusses and minuses will be determined at the end of the quarter.

I have elected to adopt an uncurved grading scheme to eliminate any sense of “competition” among students; I highly encourage you all to collaborate with and uplift each other! Furthermore, I will certainly consider adjusting the cutoffs at the end of the quarter if necessary. (I will, however, not be able to tell if or how such adjustments will be made until the end of the quarter.) **Please note:** failure to take any of the three exams without first making prior arrangements with the Course Staff will result in an automatic grade of 'F'.

## Academic Integrity

As a member of the UCSB community, it is expected that you will act with academic integrity. This means, among other things, that the work you submit should be entirely your own and not copied from any external sources. Collaboration on homework assignments is perfectly acceptable (even encouraged) but the work you submit should still be your own; you can’t have someone else write up solutions for you, nor can you consult sites like Chegg, CourseHero, ChatGPT, etc. Anyone found guilty of academic misconduct will be reported to the Academic Senate, and will receive at minimum a failing grade on the assignment in question; actions may also include failing the course, and marks being made on permanent records. Depending on the severity of the infraction, expulsion is also a possibility.

Basically, don’t cheat- please! If you’re ever struggling with course material, please come talk to me or the TAs. We are truly here for you, and want only the best for you!


## Disabled Students Program (DSP)

If you have a disability, or otherwise require accommodations for the exams and/or quizzes please reach out to the Disabled Students Program (DSP) ASAP to ensure your request(s) for accommodation can be processed. Please note that we cannot honor any requests for accommodations unless they come to us from DSP directly.


## Sections

Though we will not be tracking Section attendance this quarter, I highly encourage you to attend Section. During Section, you will work through a series of problems that are designed to help you learn the course material.

## Communication

Please note that we (the course staff) request you refrain from emailing us except in case of extreme emergency (it is up to you to decide what is an ‘emergency’). Please bring all of your questions to the course staff during either Office Hours or after Lecture/Section. We also encourage you to make use of our <a href="https://discord.gg/PqyEQX9nMm" target="_blank">Discord</a> Server. 


| **Topic** | **Redirect to...** |
|:----------|:-------------------|
| Checking answers | Office hours or Discord |
| Clarifying assignment content | Office hours or Discord |
| Assignment submission | Gradescope |
| Re-evaluation request | Gradescope |
| Question about missing grades | <a href="https://forms.gle/9p4vVWJoWag7DnST7" target="_blank">Fill Out This Form</a> |

## Course Resources/Sites

There are a couple of important sites you should be aware of for this course:

-   **Main Course Site:** https://pstat120b.github.io
This is the main site for this course this quarter - lecture, section, etc. material will be posted here. Please note that you do not need any special login to access this site - it is publicly accessible from anywhere that has internet access.

-   **Gradescope:** https://www.gradescope.com/courses/769316
Please use Gradescope for all assignment submissions. You will also take your quizzes through Gradescope.

-   **Canvas:** <link to be added ASAP>
We will primarily be using Canvas for grading purposes, and announcements - course material will not, in general, be posted to Canvas.


## Section Switching

If you want to switch sections unofficially (we do not have the ability to switch your official enrollment through GOLD), please follow the steps at <a href="https://docs.google.com/spreadsheets/d/1VI3780cx3ZQItbtflBksI3rtFWBA55wVmrgzn2YJsl8/" target="_blank">this link</a>. Any requests to switch sections that do not adhere to the guidelines posted at that link will be ignored.


## Modality

Please note that this course is **fully in-person and synchronous**; there will not be any lecture recordings made or posted, nor will Sections be recorded or offered over Zoom. Please make every effort to attend lectures and Sections!


## Disclaimer

The instructor reserves the right to modify this syllabus if he deems such modifications academically advisable. Such modifications, should they occur, will be announced publicly.


## Learning Outcomes

My main (and somewhat broad) goal for this course is:

-   To help introduce you to the theoretical underpinnings of mathematical statistics and the statistical way of thinking/writing

To this end, I have devised the following learning outcomes. By the end of this course, you should be able to:

-   Understand key theorems and results (e.g. law of iterated expectations, central limit theorem, weak and strong laws of large numbers) and how they factor in to the broader statistical framework

-   Apply common estimation techniques to simulated and real data, and accurately interpret/assess  the results (using concepts like bias, consistency, etc.)

-   Think critically about the assumptions needed to implement various statistical procedures (and to question results when such assumptions are violated)

-   Accurately express your beliefs and conclusions about problems and concepts in a mathematically and statistically rigorous manner

## Affirmations

I firmly believe that each and every one of you belongs here, at this university, in your major, and in this course. As such, I am committed to fostering a sense of inclusivity, tolerance, and respect; I ask that you please join me in this commitment. This includes things like: arriving to class and sections on time (or arriving/departing quietly if you need to arrive late/leave early), refraining from using derogatory or other hurtful language, and respecting your classmates' lived names and pronouns. 

You can update your preferred name and pronouns using UCSB’s <a href="https://secure.identity.ucsb.edu/editor/" target="_blank">Identity Services Directory Editor</a>, and read more about how UCSB uses Lived and Legal Names at <a href="https://registrar.sa.ucsb.edu/Student-Records/student-records-privacy/name-change" target="_blank">this link</a>. I am committed to using everyone’s preferred names and pronouns, so please don’t hesitate to correct me if I accidentally misidentify you.


## Some General Tips for Success

_**Form study groups**_ \
Statistics is not meant to be a lonely field! There is much we can learn from one another, and it can be an incredibly enlightening experience to discuss problems and ideas with one another. (Just make sure you don’t violate any of the Academic Integrity points listed above)

_**Be mindful of how you’re solving problems**_ \
It’s tempting to start a problem, get about halfway through, and then default to looking at the solutions or a similar worked-out example. This is not an effective way to learn! Rather, start by working through them fully and without looking at similar worked-out problems or solutions. Then you can compare your answers,  and identify any areas for potential further study. Finally, return to the problem after a few days and see if you still get stuck in the same places as you did the first time.

_**Start things early!**_ \
Make sure you’re giving yourself enough time to complete the homework assignments, study for quizzes/exams, and process the course material. I’d recommend creating a weekly schedule for yourself, and allocating time each day for PSTAT 120B material (whether that be working through the homework, studying for a quiz, or just reading lecture slides/the textbook).

_**Attend office hours (TA and Instructor) regularly**_ \
Even if you don’t have a specific question, you’re always more than welcome to sit in on Office Hours and listen to other people’s questions. (Sometimes, doing so will help you formulate your own questions!)

_**Attend lectures and Discussion Sections.**_ \
It’s true that we do not have an attendance policy, but please don’t let yourselves skimp on attendance. Studies show that regular exposure is the best way to learn material, and there really is no substitute for going to Section and Lecture. Also, while you’re in Lecture, take your own notes! Even the act of writing things down and having to synthesize what you think is important information can help you process and learn the material in real time.

_**Don’t be too hard on yourself!**_ \
Though a little stress can be a good motivating factor for some, please don’t stress yourself out too much. Your performance in this course is not an evaluation of who you are as a person!
